### ISSUE TITLE
Marker doesn't appear on non-project pages

### ISSUE THREAD

**Issue by iznaut** [biggeeves/Instance-Marker#2]
The marker no longer seems to appear on pages such as the "My Projects" view or the Control Center.

This may be a new issue in REDCap 8.3 as it still appears on these pages when I look at my 8.2.2 instance.

**Comment by dr01d3r** [comment]
REDCap v8.3.0 updated the "every page" hook logic to prevent execution on non-project pages, unless explicitly allowed, through the enable-every-page-hooks-on-system-pages configuration setting.

https://github.com/vanderbilt/redcap-external-modules/blob/master/docs/official-documentation.md

**Comment by biggeeves** [comment]
REDCap V8.3 and changed.  The every page hook was changed.  The new setting in the config file is: "enable-every-page-hooks-on-system-pages": true

The new setting has been added to the config file in Instance-Marker.  The marker now appears on every page.  Tested and approved on REDCap V8.6.0
